providers: [ "amazon","alibaba","microsoft","digitalocean","linode","vultr","google" ] # supported providers
environments: [ "test", "dev", "prod", "stage" , "staging" , "bak" ] # used for mutations
proxytype: "http"  # socks5 / http
ipinfo: "a466d34eca43d6"      # IPINFO.io API KEY
